apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: roboshop # if you don't mention specific namespace, it will attach to default namespace.
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
  ports:
  - containerPort: 80
